#-----------------------------------------------------
# Homework 3:
#-----------------------------------------------------
# 35 points total (1 point = ~2.9% of grade)
# This assignment will count as a "Journal" grade.
# You may use class notes or visit office hours.
# You cannot work on this assignment as a group.

# For each question, use the comment symbol (#) to explain the code.
# Only one or 2 sentences are necessary. This is important for partial credit.
# No comments, no credit.
#-----------------------------------------------------

# Problem 1:
# Import matplotlib, numpy, and spicy
# (5 points)
# -------
# Use this space to write code for problem 1.
# Hint: look at Lesson 4 notes.
#--------


# Problem 2a:
# Conduct online research into a subject of interest to you
# which you think could be plotted as a function of time.
# Examples could be housing cost inflation, salries for a certain job,
# or the chage in the amount of atmospheric CO2 levels.Please
# provide links or citations of the data below (aim for at leat 10 datapoints).
# (5 points)
# -------
# Use this space to write code for problem 2a.
#--------


# Problem 2b:
# Transfer the data to a python script and generate a scatter plot of the data.
# (5 points)
#--------
# Use this space to write code for problem 2b.
#--------


# Problem 2c:
# Write a function (def) to calculate a linear trendline which overlays the scatter plot.
# (7 points)
#--------
# Use this space to write code for problem 2c.
#--------


#Problem 2d:
# Choose a 2 values as inputs to your model (1 value as a prediction, 1 as a validation)
# and comment on how well you think the linear regression model fits reality. Your
# answer must be supported by printing output values for the two inputs as
# well as commenting on the r value generated by the stats.linreg report.
# The answer should be ~1 paragraph of text.
# (13 points)
#--------
# Use this space to write code for problem 2d.
#--------



#--------------------------------------------------------
# End of assignment
#--------------------------------------------------------

